version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel-app
        restart: unless-stopped
        volumes:
            - .:/var/www/html
        networks:
            - laravel-net

    nginx:
        image: nginx:latest
        container_name: laravel-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./public:/var/www/html/public
        depends_on:
            - app
        networks:
            - laravel-net

    db:
        image: mysql:5.7
        container_name: laravel-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_PASSWORD: secret
            MYSQL_USER: laravel
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - laravel-net

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: secret
        networks:
            - laravel-net

networks:
    laravel-net:
volumes:
    dbdata:
